import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1 },
  headerArea: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    zIndex: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIcon: {
    marginRight: 8,
  },
  scrollArea: { flex: 1 },
  avatarSection: { alignItems: 'center', paddingTop: 24, paddingBottom: 20 },
  avatarWrapper: {
    position: 'relative',
    padding: 4, // for the premium ring
    borderRadius: 60,
    borderWidth: 2,
    borderColor: '#D4AF37', // Gold ring
    marginBottom: 10,
  },
  avatar: {
    width: 100, height: 100, borderRadius: 50,
    justifyContent: 'center', alignItems: 'center',
  },
  avatarImage: { width: '100%', height: '100%', borderRadius: 50 },
  avatarText: { color: '#fff', fontSize: 36, fontWeight: '700' },
  uploadOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center'
  },
  premiumBadge: {
    position: 'absolute',
    bottom: -10,
    alignSelf: 'center',
    backgroundColor: '#D4AF37',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#121212',
  },
  premiumText: {
    color: '#121212',
    fontSize: 10,
    fontWeight: 'bold',
  },
  name: { marginTop: 16, fontWeight: 'bold' },
  email: { marginTop: 4, marginBottom: 15 },
  actionButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 15,
  },
  actionButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#555',
  },
  actionButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  badgesCard: {
    marginHorizontal: 20,
    marginBottom: 20,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  badgesInfo: {
    flex: 1,
    marginLeft: 15,
  },
  badgesTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  badgesSubtitle: {
    fontSize: 12,
    marginBottom: 8,
  },
  badgeIconsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  badgeMini: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#333',
    marginRight: -10, // overlap
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#121212',
  },
  statsRow: { 
    flexDirection: 'row', 
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 25,
  },
  statBox: { alignItems: 'center', flex: 1 },
  statDivider: { width: 1, height: 30 },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  addTripBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(77, 168, 218, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
  },
  addTripText: {
    color: '#4DA8DA',
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  albumsScroll: {
    paddingLeft: 20,
    paddingBottom: 20,
  },
  albumCard: {
    width: 140,
    height: 180,
    borderRadius: 16,
    marginRight: 15,
    overflow: 'hidden',
    backgroundColor: '#2A2A2A',
  },
  albumCover: {
    width: '100%',
    height: '100%',
  },
  albumOverlay: {
    position: 'absolute',
    bottom: 0, left: 0, right: 0,
    height: 80,
    justifyContent: 'flex-end',
    padding: 10,
  },
  albumName: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  albumCount: {
    color: '#ddd',
    fontSize: 12,
    marginTop: 2,
  },
  emptyAlbums: {
    marginHorizontal: 20,
    height: 120,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#333',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  emptyAlbumsText: {
    color: '#666',
    marginTop: 10,
  },
  tabsRow: { 
    flexDirection: 'row', 
    justifyContent: 'space-around', 
    borderBottomWidth: 1, 
    borderBottomColor: '#333',
    marginHorizontal: 20,
  },
  tabButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  footer: { textAlign: 'center', marginTop: 30, marginBottom: 20 },
});

export default styles;
